#!/usr/bin/env node
/*
 * Projects the workspace's single .env (PRD §14) into apps/web/.env.local.
 *
 * Next.js only reads .env files from its own project directory, and inlining
 * NEXT_PUBLIC_* values into the client bundle happens through that mechanism —
 * next.config's `env` option is not a reliable substitute under Turbopack. So
 * the root file stays the one place anyone edits, and this copies the public
 * half of it to where Next will look.
 *
 * The generated file is gitignored; this script is not.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const source = join(root, ".env");
const target = join(root, "apps", "web", ".env.local");

if (!existsSync(source)) {
  console.warn("[sync-env] no .env at the workspace root — copy .env.example to .env first");
  process.exit(0);
}

const publicLines = readFileSync(source, "utf8")
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line.startsWith("NEXT_PUBLIC_"))
  // Strip trailing inline comments, which dotenv would otherwise treat as value.
  .map((line) => line.replace(/\s+#.*$/, ""));

const banner = [
  "# Generated by scripts/sync-env.mjs from the workspace root .env — do not edit.",
  "# Edit the root .env instead, then re-run `pnpm sync-env`.",
  "",
];

writeFileSync(target, [...banner, ...publicLines, ""].join("\n"), "utf8");
console.log(`[sync-env] wrote ${publicLines.length} public variables to apps/web/.env.local`);
